//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesEncrypter.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NotesEncrypter.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EnterMessage {
            get {
                return ResourceManager.GetString("EnterMessage", resourceCulture);
            }
        }
        
        internal static string EnterKey {
            get {
                return ResourceManager.GetString("EnterKey", resourceCulture);
            }
        }
        
        internal static string EnterText {
            get {
                return ResourceManager.GetString("EnterText", resourceCulture);
            }
        }
        
        internal static string Encrypt {
            get {
                return ResourceManager.GetString("Encrypt", resourceCulture);
            }
        }
        
        internal static string Decrypt {
            get {
                return ResourceManager.GetString("Decrypt", resourceCulture);
            }
        }
        
        internal static string SymbolTable {
            get {
                return ResourceManager.GetString("SymbolTable", resourceCulture);
            }
        }
        
        internal static string SymbolTableSettings {
            get {
                return ResourceManager.GetString("SymbolTableSettings", resourceCulture);
            }
        }
        
        internal static string SelectTable {
            get {
                return ResourceManager.GetString("SelectTable", resourceCulture);
            }
        }
        
        internal static string ShareMessage {
            get {
                return ResourceManager.GetString("ShareMessage", resourceCulture);
            }
        }
        
        internal static string HideKey {
            get {
                return ResourceManager.GetString("HideKey", resourceCulture);
            }
        }
        
        internal static string UsePresetKey {
            get {
                return ResourceManager.GetString("UsePresetKey", resourceCulture);
            }
        }
        
        internal static string PresetKey {
            get {
                return ResourceManager.GetString("PresetKey", resourceCulture);
            }
        }
        
        internal static string KeySettings {
            get {
                return ResourceManager.GetString("KeySettings", resourceCulture);
            }
        }
        
        internal static string CiphersGallery {
            get {
                return ResourceManager.GetString("CiphersGallery", resourceCulture);
            }
        }
        
        internal static string VigeneresCipherName {
            get {
                return ResourceManager.GetString("VigeneresCipherName", resourceCulture);
            }
        }
        
        internal static string VigeneresCipherDescription {
            get {
                return ResourceManager.GetString("VigeneresCipherDescription", resourceCulture);
            }
        }
        
        internal static string CeasarCipherName {
            get {
                return ResourceManager.GetString("CeasarCipherName", resourceCulture);
            }
        }
        
        internal static string CeasarCipherDescription {
            get {
                return ResourceManager.GetString("CeasarCipherDescription", resourceCulture);
            }
        }
    }
}
